export const myProjects = [
  {
    id: 14,
    categoria: "react",
    imgUrl: "/projecs/weather app.png",
    title: "weather By React",
    LiveDemo: "https://weatherappwithreact1.netlify.app/",
    RepoLink: "https://github.com/MohamedGlalAbdelazeem/Weather-App",
  },
  {
    id: 1,
    categoria: "htmlcss",
    imgUrl: "/projecs/E-commerce2.png",
    title: "HTML5 & CSS3 & Bootstrap project",
    LiveDemo: "https://mohamedglalabdelazeem.github.io/E-commerce/",
    RepoLink: "https://github.com/MohamedGlalAbdelazeem/E-commerce",
  },
  {
    id: 2,
    categoria: "htmlcss",
    imgUrl: "/projecs/bootstrab.png",
    title: "HTML5 & CSS3 & Bootstrap project",
    LiveDemo: "https://mohamedglalabdelazeem.github.io/Bootsrap-Project/",
    RepoLink: "https://github.com/MohamedGlalAbdelazeem/Bootsrap-Project",
  },
  {
    id: 3,
    categoria: "htmlcss",
    imgUrl: "/projecs/bootstrab2.png",
    title: "HTML5 & CSS3 & Bootstrap project",
    LiveDemo: "https://mohamedglalabdelazeem.github.io/Bootstrap-Project/",
    RepoLink: "https://github.com/MohamedGlalAbdelazeem/Bootstrap-Project",
  },
  {
    id: 4,
    categoria: "htmlcss",
    imgUrl: "/projecs/project10.png",
    title: "HTML5 & CSS3  project",
    LiveDemo: "https://mohamedglalabdelazeem.github.io/landing_page_3/",
    RepoLink: "https://github.com/MohamedGlalAbdelazeem/landing_page_3",
  },
  {
    id: 5,
    categoria: "htmlcss",
    imgUrl: "/projecs/project9.png",
    title: "HTML5 & CSS3 ",
    LiveDemo: "https://mohamedglalabdelazeem.github.io/Landing-page_2/",
    RepoLink: "https://github.com/MohamedGlalAbdelazeem/Landing-page_2",
  },
  {
    id: 6,
    categoria: "htmlcss",
    imgUrl: "/projecs/landing page.png",
    title: "HTML5 & CSS3 Landing page ",
    LiveDemo: "https://mohamedglalabdelazeem.github.io/landing_page1/",
    RepoLink: "https://github.com/MohamedGlalAbdelazeem/landing_page1",
  },
  {
    id: 7,
    categoria: "htmlcss",
    imgUrl: "/projecs/dashboard.png",
    title: "HTML5 & CSS3 Dashboard",
    LiveDemo: "https://mohamedglalabdelazeem.github.io/Dashboard/",
    RepoLink: "https://github.com/MohamedGlalAbdelazeem/Dashboard",
  },
  {
    id: 8,
    categoria: "js",
    imgUrl: "/projecs/CRUDS.png",
    title: "javascrip CRUDP Project",
    LiveDemo: "https://mohamedglalabdelazeem.github.io/CRUDS_SYSTEM/",
    RepoLink: "https://github.com/MohamedGlalAbdelazeem/CRUDS_SYSTEM",
  },
  {
    id: 16,
    categoria: "js",
    imgUrl: "/projecs/project4.png",
    title: "javascrip Image Editor Project",
    LiveDemo: "https://mohamedglalabdelazeem.github.io/Image-Editor/",
    RepoLink: "https://github.com/MohamedGlalAbdelazeem/Image-Editor/tree/main",
  },
  {
    id: 17,
    categoria: "js",
    imgUrl: "/projecs/project7.png",
    title: "  Prayer-Timings Project",
    LiveDemo: "https://mohamedglalabdelazeem.github.io/Prayer-Timings/",
    RepoLink:
      "https://github.com/MohamedGlalAbdelazeem/Prayer-Timings/tree/main",
  },
  {
    id: 18,
    categoria: "js",
    imgUrl: "/projecs/project5.png",
    title: "  Muslim-website Project",
    LiveDemo: "https://mohamedglalabdelazeem.github.io/Muslim-website/",
    RepoLink:
      "https://github.com/MohamedGlalAbdelazeem/Muslim-website/tree/main",
  },
  {
    id: 19,
    categoria: "js",
    imgUrl: "/projecs/E-commerce.png",
    title: "Shoes Store Project",
    LiveDemo: "https://mohamedglalabdelazeem.github.io/Shoes-Store/",
    RepoLink: "https://github.com/MohamedGlalAbdelazeem/Shoes-Store/tree/main",
  },
  {
    id: 20,
    categoria: "js",
    imgUrl: "/projecs/project3.png",
    title: " car E-commerce Project",
    LiveDemo: "https://mohamedglalabdelazeem.github.io/E-Commerce-for-cars/",
    RepoLink:
      "https://github.com/MohamedGlalAbdelazeem/E-Commerce-for-cars/tree/main",
  },
  {
    id: 130,
    categoria: "react",
    imgUrl: "/public/projecs/MyProfile.png",
    title: "My_Portfolio",
    LiveDemo: "https://mohamedgalal2.netlify.app/",
    RepoLink: "https://github.com/MohamedGlalAbdelazeem/My_Portfolio",
  },
  {
    id: 13,
    categoria: "react",
    imgUrl: "/projecs/Todolist.png",
    title: "React ToDoApp",
    LiveDemo: "",
    RepoLink: "",
  },

  {
    id: 30,
    categoria: "react",
    imgUrl: "/projecs/loan form app.png",
    title: "Loan App Form App ",
    LiveDemo: " ",
    RepoLink:
      "https://github.com/MohamedGlalAbdelazeem/Loan-app-form/tree/main",
  },
  {
    id: 160,
    categoria: "react",
    imgUrl: "/projecs/xoo.png",
    title: "X-O Game By React",
    LiveDemo: "https://x-ogame2.netlify.app/",
    RepoLink: "https://github.com/MohamedGlalAbdelazeem/X-O-Game",
  },
];
